modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="letmefeedyou" #mandatory
version="1.20.1-1.0.0" #mandatory
displayName="Let Me Feed You!" #mandatory
authors="Rinko1231" #optional
description="Players can feed each other."
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.letmefeedyou]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.letmefeedyou]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
